# Generated by Django 4.2.7 on 2023-12-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='volume',
        ),
    ]
